config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'
  resources :books, only: [:search, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_cache_key

  def session_cache_key
    session[:time_of_first_visit]
  end
  helper_method :session_cache_key

  private

  def set_cache_key
    session[:time_of_first_visit] ||= Time.zone.now
  end
end

app/controllers/books_controller.rb
require 'net/http'
require 'json'
require 'will_paginate/array'

class BooksController < ApplicationController
  ALL_BOOKS_URL = 'https://skookum-test-api.herokuapp.com/api/v1/books'.freeze

  def index
    @books = filtered_books
    @paginated_books = @books.paginate(page: page_params[:page], per_page: 20)
  end

  def search_params
    params.require(:q).permit(:title, :author, :year, :isbn)
  end
  helper_method :search_params

  def page_params
    params.permit(:page)
  end

  private

  # @return Array<Hash[title:, author:, year:, isbn:]>
  def all_books
    Rails.cache.fetch("#{session_cache_key}/books#all_books", expires_in: 1.hour) do
      response = Net::HTTP.get(URI(ALL_BOOKS_URL))
      JSON.parse(response)
    end
  rescue JSON::ParserError
    {}
  end

  def filtered_books
    if params[:q].present?
      all_books.select { |book| book.slice(*search_params.keys) == search_params }
    else
      all_books
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  %w[title author year isbn].each do |book_param|
    define_method "all_book_#{book_param.pluralize}" do
      Rails.cache.fetch("#{session_cache_key}/books#all_book_#{book_param}", expires_in: 1.hour) do
        @books.map { |book| book[book_param].presence }.compact.uniq.sort
      end
    end
  end
end

app/views/application/_header.html.haml
%h1.logo Skookum Bookum
%nav
  .nav-item Filters
  - %w[author title year isbn].each do |book_param|
    - if params[:q] && params[:q][book_param]
      = link_to "X | #{params[:q][book_param]}", books_path(q: search_params.except(book_param)), class: 'dropdown-selected nav-item'
    - else
      .nav-item.dropdown
        = link_to book_param.titleize, '#', class: 'dropdown-btn'
        .dropdown-content
          - send("all_book_#{book_param.pluralize}").each do |b|
            - book_path_params = params[:q] ? search_params : {}
            = link_to b, books_path(q: book_path_params.merge(book_param => b))

app/views/books/_item.html.haml
.book-list-item
  .title
    = "Title: #{book['title']}"
  .author
    = "Author: #{book['author']}"
  .year
    = "Year: #{book['year']}"
  .isbn
    = "ISBN: #{book['isbn']}"

app/views/books/index.html.haml
.book-list
  - @paginated_books.each do |book|
    = render 'item', book: book
  = will_paginate @paginated_books

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkookumBookum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header' %>
    <%= yield %>
  </body>
</html>